JANEIRO = 'janeiro'
FEVEREIRO = 'fevereiro'
MARCO = 'marco'
ABRIL = 'abril'
MAIO = 'maio'
JUNHO = 'junho'
JULHO = 'julho'
AGOSTO = 'agosto'
SETEMBRO = 'setembro'
OUTUBRO = 'outubro'
NOVEMBRO = 'novembro'
DEZEMBRO = 'dezembro'

NUM_JANEIRO = 1
NUM_FEVEREIRO = 2
NUM_MARCO = 3
NUM_ABRIL = 4
NUM_MAIO = 5
NUM_JUNHO = 6
NUM_JULHO = 7
NUM_AGOSTO = 8
NUM_SETEMBRO = 9
NUM_OUTUBRO = 10
NUM_NOVEMBRO = 11
NUM_DEZEMBRO = 12

DICT_MES_NUM = {
    JANEIRO: NUM_JANEIRO,
    FEVEREIRO: NUM_FEVEREIRO,
    MARCO: NUM_MARCO,
    ABRIL: NUM_ABRIL,
    MAIO: NUM_MAIO,
    JUNHO: NUM_JUNHO,
    JULHO: NUM_JULHO,
    AGOSTO: NUM_AGOSTO,
    SETEMBRO: NUM_SETEMBRO,
    OUTUBRO: NUM_OUTUBRO,
    NOVEMBRO: NUM_NOVEMBRO,
    DEZEMBRO: NUM_DEZEMBRO
    }

DICT_NUM_MES = {
    NUM_JANEIRO: JANEIRO,
    NUM_FEVEREIRO: FEVEREIRO,
    NUM_MARCO: MARCO,
    NUM_ABRIL: ABRIL,
    NUM_MAIO: MAIO,
    NUM_JUNHO: JUNHO,
    NUM_JULHO: JULHO,
    NUM_AGOSTO: AGOSTO,
    NUM_SETEMBRO: SETEMBRO,
    NUM_OUTUBRO: OUTUBRO,
    NUM_NOVEMBRO: NOVEMBRO,
    NUM_DEZEMBRO: DEZEMBRO
    }
